In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
data = pd.read_csv('Iris.csv')

In [3]:
columns = data.columns
columns = list(columns)
print(columns)

['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']


In [4]:
data_values = pd.DataFrame(data,columns=columns[1:-1],dtype=np.float32)
print(data_values.head)

<bound method NDFrame.head of      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
5              5.4           3.9            1.7           0.4
6              4.6           3.4            1.4           0.3
7              5.0           3.4            1.5           0.2
8              4.4           2.9            1.4           0.2
9              4.9           3.1            1.5           0.1
10             5.4           3.7            1.5           0.2
11             4.8           3.4            1.6           0.2
12             4.8           3.0            1.4           0.1
13             4.3           3.0            1.1           0.1
14             5.8           4.0        

In [5]:
data_targets = data['Species']
print(data_targets.head)

<bound method NDFrame.head of 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17        Iris-setosa
18        Iris-setosa
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25        Iris-setosa
26        Iris-setosa
27        Iris-setosa
28        Iris-setosa
29        Iris-setosa
            ...      
120    Iris-virginica
121    Iris-virginica
122    Iris-virginica
123    Iris-virginica
124    Iris-virginica
125    Iris-virginica
126    Iris-virginica
127    Iris-virginica
128    Iris-virginica
129    Iris-virginica
130    Iris-virginica
131    Iris-virginica
132    Iris-virginica
13

In [6]:
avaliable_labels = data_targets.unique()
print(avaliable_labels)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [7]:
data_targets = data_targets.replace({avaliable_labels[0]:0,avaliable_labels[1]:1,avaliable_labels[2]:2})
print(data_targets)

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
120    2
121    2
122    2
123    2
124    2
125    2
126    2
127    2
128    2
129    2
130    2
131    2
132    2
133    2
134    2
135    2
136    2
137    2
138    2
139    2
140    2
141    2
142    2
143    2
144    2
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64


In [8]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [9]:
data_onehot_targets = to_categorical(data_targets)

In [10]:
print(data_onehot_targets[:10])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [11]:
data_onehot_targets.dtype

dtype('float32')

In [12]:
from sklearn.cross_validation import train_test_split

C:\Users\Gowtham\Anaconda3\envs\flower\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [13]:
train_data,test_data,train_targets,test_targets = train_test_split(data_values,data_onehot_targets)

In [14]:
print(train_data.shape,train_targets.shape)

(112, 4) (112, 3)


In [15]:
print(test_data.shape,test_targets.shape)

(38, 4) (38, 3)


In [16]:
weights = {'wf1':tf.Variable(tf.random_normal([4,16])),
          'wf2' : tf.Variable(tf.random_normal([16,32])),
          'wfinal': tf.Variable(tf.random_normal([32,3]))}
biases = {'bf1': tf.Variable(tf.random_normal([16])),
         'bf2': tf.Variable(tf.random_normal([32])),
         'bfinal': tf.Variable(tf.random_normal([3]))}

In [17]:
def z_score_normalization(inputs):
    mean = inputs.mean()
    std = inputs.std()
    normalized_values = list()
    for x in inputs:
        z_score = (x - mean)/std
        normalized_values.append(z_score)
    normalized_values = np.array(normalized_values)
    return normalized_values

In [18]:
sample = data_values[columns[1]]

In [19]:
nv = z_score_normalization(sample)

In [20]:
for column in columns[1:-1]:
    train_data[column] = z_score_normalization(train_data[column])
    test_data[column] = z_score_normalization(test_data[column])

C:\Users\Gowtham\Anaconda3\envs\flower\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\Gowtham\Anaconda3\envs\flower\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


In [21]:
train_data.head

<bound method NDFrame.head of      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
53       -0.469540     -1.657597       0.071231      0.058204
147       0.759161     -0.074703       0.775165      0.989465
60       -1.083890     -2.335981      -0.222074     -0.340908
47       -1.575371      0.377553      -1.453958     -1.405207
40       -1.083890      1.055936      -1.512619     -1.272170
39       -0.961020      0.829808      -1.395297     -1.405207
51        0.636291      0.377553       0.364537      0.324279
86        1.004901      0.151425       0.481859      0.324279
41       -1.698241     -1.657597      -1.512619     -1.272170
64       -0.346670     -0.300831      -0.163413      0.058204
99       -0.223800     -0.526959       0.129893      0.058204
106      -1.206760     -1.205342       0.364537      0.590353
97        0.390550     -0.300831       0.247215      0.058204
73        0.267680     -0.526959       0.481859     -0.074833
90       -0.469540     -0.979214       0

In [22]:
test_data.head

<bound method NDFrame.head of      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
131       2.496673      1.683648       1.568162      1.242531
0        -0.723279      0.945433      -1.050034     -1.060697
113      -0.033290     -1.515283       0.835067      1.242531
42       -1.528267      0.207218      -1.102398     -1.060697
33       -0.263286      2.667934      -1.050034     -1.060697
23       -0.723279      0.453290      -0.892943     -0.676826
38       -1.528267     -0.284925      -1.102398     -1.060697
25       -0.838277     -0.284925      -0.945307     -1.060697
77        1.116693     -0.284925       0.835067      0.858659
70        0.196707      0.207218       0.730339      0.986616
61        0.196707     -0.284925       0.416155      0.602745
19       -0.723279      1.683648      -0.997670     -0.932740
37       -0.953275     -0.038854      -0.997670     -1.188654
144       1.116693      0.453290       1.201614      1.882316
27       -0.608281      0.945433      -0

In [23]:
train_data = train_data.astype(np.float32)
test_data = test_data.astype(np.float32)

In [24]:
def next_batch(values,batch,batch_size):
    start = batch*batch_size
    end = start + batch_size
    return values[start:end]

In [25]:
def neuralnet(inputs):
    layer1 = tf.add(tf.matmul(inputs,weights['wf1']),biases['bf1'])
    layer1 = tf.nn.relu(layer1)
    layer2 = tf.add(tf.matmul(layer1,weights['wf2']),biases['bf2'])
    layer2 = tf.nn.relu(layer2)
    logits = tf.add(tf.matmul(layer2,weights['wfinal']),biases['bfinal'])
    out = tf.nn.softmax(logits)
    return logits,out

In [26]:
batch_size = 10
learning_rate = 0.1
epochs = 10

In [27]:
inputs = tf.placeholder(tf.float32,[None,4])
targets = tf.placeholder(tf.float32,[None,3])

logits,out = neuralnet(inputs)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,labels=targets))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)
correct_pred = tf.equal(tf.argmax(logits,1),tf.argmax(targets,1))
accuracy = tf.reduce_mean(tf.cast(correct_pred,tf.float32))

In [28]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoch in range(epochs):
        for batch in range(len(train_data)//batch_size):
            x_batch = next_batch(train_data,batch,batch_size)
            y_batch = next_batch(train_targets,batch,batch_size)
            
            opt = sess.run(optimizer,feed_dict={inputs:x_batch,targets:y_batch})
            train_loss = sess.run(cost,feed_dict={inputs:x_batch,targets:y_batch})
            test_loss = sess.run(cost,feed_dict={inputs:test_data,targets:test_targets})
            acc = sess.run(accuracy,feed_dict={inputs:test_data,targets:test_targets})
            
            if batch % 10 == 0:
                print('epoch {},batch {},train_loss {:.4f},test_loss {:.4f},accuracy {:.4f}'.format(epoch+1,batch,train_loss,
                                                                                                   test_loss,acc))

epoch 1,batch 0,train_loss 5.5570,test_loss 6.8270,accuracy 0.5000
epoch 1,batch 10,train_loss 0.0277,test_loss 0.4805,accuracy 0.8947
epoch 2,batch 0,train_loss 0.0309,test_loss 0.2659,accuracy 0.9474
epoch 2,batch 10,train_loss 0.0677,test_loss 0.3001,accuracy 0.8947
epoch 3,batch 0,train_loss 0.0153,test_loss 0.2768,accuracy 0.8947
epoch 3,batch 10,train_loss 0.0552,test_loss 0.5512,accuracy 0.8421
epoch 4,batch 0,train_loss 0.0171,test_loss 0.4661,accuracy 0.8684
epoch 4,batch 10,train_loss 0.0455,test_loss 0.4503,accuracy 0.8684
epoch 5,batch 0,train_loss 0.0102,test_loss 0.4242,accuracy 0.8684
epoch 5,batch 10,train_loss 0.0484,test_loss 0.4332,accuracy 0.8684
epoch 6,batch 0,train_loss 0.0083,test_loss 0.4126,accuracy 0.8684
epoch 6,batch 10,train_loss 0.0224,test_loss 0.3972,accuracy 0.8947
epoch 7,batch 0,train_loss 0.0060,test_loss 0.3863,accuracy 0.8947
epoch 7,batch 10,train_loss 0.0490,test_loss 0.4239,accuracy 0.8947
epoch 8,batch 0,train_loss 0.0072,test_loss 0.4082,accu

In [29]:
sample_inputs = test_data[:20]
sample_inputs_true_labels = test_targets[:20]
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    predictions = sess.run(out,feed_dict={inputs:sample_inputs})
    predictions = np.argmax(predictions,1)

In [30]:
print(predictions)

[1 2 1 2 2 2 2 2 1 1 1 2 2 1 2 1 1 2 1 1]


In [31]:
predictions.dtype

dtype('int64')

In [32]:
def convert_to_classes(labels):
    predicted_classes = list()
    for label in labels:
        label = avaliable_labels[label]
        predicted_classes.append(label)
    return predicted_classes

In [33]:
predicted_classes = convert_to_classes(predictions)
print('These are predicted labels')
print(predicted_classes)

These are predicted labels
['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor']


In [34]:
sample_inputs_true_labels = np.argmax(sample_inputs_true_labels,1)
sample_inputs_true_labels = convert_to_classes(sample_inputs_true_labels)
print('These are True labels')
print(sample_inputs_true_labels)

These are True labels
['Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica']
